// Mock data for demonstration purposes
// This provides realistic data for all dashboards without requiring database entries

export const DEMO_USER_ID = "demo-user-id";

export const mockJobs = [
  {
    id: "job-001",
    title: "Produce Delivery to Nairobi Market",
    shipper_id: DEMO_USER_ID,
    status: "in_transit" as const,
    pickup_label: "Meru Farms, Meru County",
    pickup_lat: -0.0470,
    pickup_lng: 37.6493,
    drop_label: "Wakulima Market, Nairobi",
    drop_lat: -1.2864,
    drop_lng: 36.8172,
    budget_cents: 4500000,
    weight_kg: 2500,
    cargo_type: "produce" as const,
    urgency: true,
    scheduled_pickup: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "job-002",
    title: "Construction Materials Transport",
    shipper_id: DEMO_USER_ID,
    status: "bidding" as const,
    pickup_label: "Bamburi Cement, Mombasa",
    pickup_lat: -4.0435,
    pickup_lng: 39.6682,
    drop_label: "Kisumu Construction Site",
    drop_lat: -0.1022,
    drop_lng: 34.7617,
    budget_cents: 8500000,
    weight_kg: 15000,
    cargo_type: "cement" as const,
    urgency: false,
    scheduled_pickup: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "job-003",
    title: "Electronics Shipment",
    shipper_id: DEMO_USER_ID,
    status: "posted" as const,
    pickup_label: "Samsung Warehouse, Nairobi",
    pickup_lat: -1.2921,
    pickup_lng: 36.8219,
    drop_label: "Nakuru Electronics Hub",
    drop_lat: -0.3031,
    drop_lng: 36.0800,
    budget_cents: 3200000,
    weight_kg: 800,
    cargo_type: "electronics" as const,
    urgency: true,
    scheduled_pickup: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "job-004",
    title: "Furniture Delivery",
    shipper_id: DEMO_USER_ID,
    status: "delivered" as const,
    pickup_label: "IKEA Warehouse, Nairobi",
    pickup_lat: -1.3028,
    pickup_lng: 36.7073,
    drop_label: "Eldoret Mall",
    drop_lat: 0.5143,
    drop_lng: 35.2698,
    budget_cents: 5500000,
    weight_kg: 3500,
    cargo_type: "furniture" as const,
    urgency: false,
    scheduled_pickup: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-005",
    title: "Medical Supplies Urgent",
    shipper_id: DEMO_USER_ID,
    status: "assigned" as const,
    pickup_label: "Kenya Medical Supplies, Nairobi",
    pickup_lat: -1.2741,
    pickup_lng: 36.8155,
    drop_label: "Machakos General Hospital",
    drop_lat: -1.5177,
    drop_lng: 37.2634,
    budget_cents: 2800000,
    weight_kg: 450,
    cargo_type: "medical_supplies" as const,
    urgency: true,
    scheduled_pickup: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockBids = [
  {
    id: "bid-001",
    job_id: "job-002",
    driver_id: "driver-001",
    amount_cents: 7800000,
    eta_minutes: 480,
    status: "active" as const,
    note: "I have experience with heavy loads. Can start immediately.",
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    driver_name: "James Mwangi",
    driver_rating: 4.8,
    driver_phone: "+254722123456",
    completed_jobs: 156,
  },
  {
    id: "bid-002",
    job_id: "job-002",
    driver_id: "driver-002",
    amount_cents: 8200000,
    eta_minutes: 420,
    status: "active" as const,
    note: "Premium truck with GPS tracking. 10 years experience.",
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    driver_name: "Peter Ochieng",
    driver_rating: 4.9,
    driver_phone: "+254733456789",
    completed_jobs: 234,
  },
  {
    id: "bid-003",
    job_id: "job-002",
    driver_id: "driver-003",
    amount_cents: 7500000,
    eta_minutes: 540,
    status: "active" as const,
    note: "Competitive pricing. Reliable delivery guaranteed.",
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    driver_name: "Samuel Kiprop",
    driver_rating: 4.6,
    driver_phone: "+254744789012",
    completed_jobs: 89,
  },
  {
    id: "bid-004",
    job_id: "job-003",
    driver_id: "driver-001",
    amount_cents: 2900000,
    eta_minutes: 180,
    status: "active" as const,
    note: "Available for immediate pickup.",
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    driver_name: "James Mwangi",
    driver_rating: 4.8,
    driver_phone: "+254722123456",
    completed_jobs: 156,
  },
];

export const mockHubs = [
  {
    id: "hub-001",
    hub_name: "Nairobi Central Transit Hub",
    hub_type: "transit_stop" as const,
    owner_id: DEMO_USER_ID,
    location_label: "Industrial Area, Nairobi",
    lat: -1.3032,
    lng: 36.8516,
    capacity: 50,
    fee_model: "per_checkin" as const,
    fee_cents: 50000,
    is_active: true,
    verification_status: "approved" as const,
    operating_hours: "24/7",
    security_features: { guards: true, cameras: true, fencing: true, lighting: true },
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "hub-002",
    hub_name: "Mombasa Port Yard",
    hub_type: "micro_hub" as const,
    owner_id: DEMO_USER_ID,
    location_label: "Mombasa Port, Mombasa",
    lat: -4.0435,
    lng: 39.6682,
    capacity: 100,
    fee_model: "daily" as const,
    fee_cents: 200000,
    is_active: true,
    verification_status: "approved" as const,
    operating_hours: "6:00 AM - 10:00 PM",
    security_features: { guards: true, cameras: true, fencing: true, lighting: true },
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "hub-003",
    hub_name: "Nakuru Rest Stop",
    hub_type: "transit_stop" as const,
    owner_id: DEMO_USER_ID,
    location_label: "Nakuru Town",
    lat: -0.3031,
    lng: 36.0800,
    capacity: 25,
    fee_model: "per_checkin" as const,
    fee_cents: 30000,
    is_active: true,
    verification_status: "approved" as const,
    operating_hours: "5:00 AM - 11:00 PM",
    security_features: { guards: false, cameras: true, fencing: true, lighting: true },
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockCheckins = [
  {
    id: "checkin-001",
    hub_id: "hub-001",
    user_id: DEMO_USER_ID,
    event_type: "checkin",
    fee_charged_cents: 50000,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hub_name: "Nairobi Central Transit Hub",
  },
  {
    id: "checkin-002",
    hub_id: "hub-001",
    user_id: DEMO_USER_ID,
    event_type: "checkout",
    fee_charged_cents: 0,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    hub_name: "Nairobi Central Transit Hub",
  },
  {
    id: "checkin-003",
    hub_id: "hub-002",
    user_id: DEMO_USER_ID,
    event_type: "checkin",
    fee_charged_cents: 200000,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hub_name: "Mombasa Port Yard",
  },
  {
    id: "checkin-004",
    hub_id: "hub-002",
    user_id: DEMO_USER_ID,
    event_type: "checkout",
    fee_charged_cents: 0,
    created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    hub_name: "Mombasa Port Yard",
  },
];

export const mockTransactions = [
  {
    id: "txn-001",
    user_id: DEMO_USER_ID,
    amount_cents: 4500000,
    direction: "in",
    description: "Payment for Job: Produce Delivery to Nairobi",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    job_id: "job-001",
  },
  {
    id: "txn-002",
    user_id: DEMO_USER_ID,
    amount_cents: 50000,
    direction: "out",
    description: "Hub Fee: Nairobi Central Transit Hub",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hub_id: "hub-001",
  },
  {
    id: "txn-003",
    user_id: DEMO_USER_ID,
    amount_cents: 5500000,
    direction: "in",
    description: "Payment for Job: Furniture Delivery",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    job_id: "job-004",
  },
  {
    id: "txn-004",
    user_id: DEMO_USER_ID,
    amount_cents: 250000,
    direction: "in",
    description: "Tip from customer",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "txn-005",
    user_id: DEMO_USER_ID,
    amount_cents: 200000,
    direction: "out",
    description: "Hub Fee: Mombasa Port Yard",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hub_id: "hub-002",
  },
  {
    id: "txn-006",
    user_id: DEMO_USER_ID,
    amount_cents: 3200000,
    direction: "in",
    description: "Payment for Job: Electronics Shipment",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "txn-007",
    user_id: DEMO_USER_ID,
    amount_cents: 8500000,
    direction: "in",
    description: "Payment for Job: Construction Materials",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "txn-008",
    user_id: DEMO_USER_ID,
    amount_cents: 5000000,
    direction: "out",
    description: "Payout to M-Pesa",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockCompletedJobs = [
  {
    id: "completed-001",
    title: "Produce Delivery to Nairobi Market",
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 4500000,
    pickupLabel: "Meru Farms, Meru County",
    dropLabel: "Wakulima Market, Nairobi",
  },
  {
    id: "completed-002",
    title: "Furniture Delivery to Eldoret",
    completedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 5500000,
    pickupLabel: "IKEA Warehouse, Nairobi",
    dropLabel: "Eldoret Mall",
  },
  {
    id: "completed-003",
    title: "Electronics Shipment",
    completedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 3200000,
    pickupLabel: "Samsung Warehouse, Nairobi",
    dropLabel: "Nakuru Electronics Hub",
  },
  {
    id: "completed-004",
    title: "Construction Materials Transport",
    completedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 8500000,
    pickupLabel: "Bamburi Cement, Mombasa",
    dropLabel: "Kisumu Construction Site",
  },
  {
    id: "completed-005",
    title: "Medical Supplies Delivery",
    completedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 2800000,
    pickupLabel: "Kenya Medical Supplies",
    dropLabel: "Machakos General Hospital",
  },
  {
    id: "completed-006",
    title: "Dairy Products Transport",
    completedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 1800000,
    pickupLabel: "Brookside Dairy, Ruiru",
    dropLabel: "Carrefour Supermarket, Nairobi",
  },
];

export const mockDailyEarnings = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  const hasEarnings = Math.random() > 0.3;
  return {
    date: date.toLocaleDateString("en-US", { month: "short", day: "2-digit" }),
    earnings: hasEarnings ? Math.floor(Math.random() * 80000 + 20000) / 100 : 0,
    jobs: hasEarnings ? Math.floor(Math.random() * 3) + 1 : 0,
  };
});

export const mockMonthlyEarnings = [
  { month: "Aug 2025", earnings: 125000 },
  { month: "Sep 2025", earnings: 185000 },
  { month: "Oct 2025", earnings: 142000 },
  { month: "Nov 2025", earnings: 198000 },
  { month: "Dec 2025", earnings: 165000 },
  { month: "Jan 2026", earnings: 215000 },
];

export const mockEarningsSummary = {
  totalEarnings: 24500000,
  jobEarnings: 24500000,
  hubFees: 250000,
  tips: 250000,
  weeklyEarnings: 10000000,
  monthlyEarnings: 21700000,
  pendingPayouts: 0,
  completedPayouts: 5000000,
};

export const mockDriverStats = {
  availableJobs: 12,
  weeklyEarnings: 10000000,
  rating: 4.8,
  completedJobs: 156,
  walletBalance: 12500000,
};

export const mockShipperStats = {
  activeJobs: 3,
  inTransit: 2,
  delivered: 45,
  totalSpent: 85000000,
};

export const mockLandownerStats = {
  activeHubs: 3,
  monthlyEarnings: 3500000,
  totalCheckins: 234,
  growthPercent: 15,
};

export const mockRecurringRoutes = [
  {
    id: "route-001",
    title: "Daily Produce Run",
    cadence: "daily",
    pickup_label: "Meru Farms",
    drop_label: "Nairobi Market",
    budget_cents: 4500000,
    is_active: true,
    next_run_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    total_jobs_created: 45,
  },
  {
    id: "route-002",
    title: "Weekly Electronics Supply",
    cadence: "weekly",
    pickup_label: "Samsung Warehouse",
    drop_label: "Nakuru Hub",
    budget_cents: 3200000,
    is_active: true,
    days_of_week: [1, 4],
    next_run_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    total_jobs_created: 12,
  },
];

export const mockGPSLogs = [
  { lat: -1.2921, lng: 36.8219, created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString() },
  { lat: -1.2800, lng: 36.8100, created_at: new Date(Date.now() - 50 * 60 * 1000).toISOString() },
  { lat: -1.2650, lng: 36.7950, created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString() },
  { lat: -1.2500, lng: 36.7800, created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { lat: -1.2350, lng: 36.7650, created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
  { lat: -1.2200, lng: 36.7500, created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
];

// Admin dashboard mock data
export const mockAdminStats = {
  totalUsers: 1247,
  activeJobs: 89,
  pendingApprovals: 23,
  openTickets: 12,
  totalRevenue: 125000000,
  driversOnline: 156,
};

export const mockPendingApprovals = [
  {
    id: "approval-001",
    type: "driver",
    name: "John Kamau",
    submitted: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    documents: ["License", "ID", "Vehicle Photos"],
  },
  {
    id: "approval-002",
    type: "landowner",
    name: "Mary Wanjiku",
    submitted: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    documents: ["Land Title", "ID"],
  },
  {
    id: "approval-003",
    type: "shipper",
    name: "ABC Logistics Ltd",
    submitted: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    documents: ["Business Registration", "KRA Pin"],
  },
];

export const mockSupportTickets = [
  {
    id: "ticket-001",
    category: "Payment Issue",
    message: "I haven't received my payment for job #1234",
    status: "open",
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    created_by_name: "Peter Driver",
  },
  {
    id: "ticket-002",
    category: "Dispute",
    message: "Driver delivered damaged goods",
    status: "in_progress",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_by_name: "Jane Shipper",
  },
  {
    id: "ticket-003",
    category: "Account",
    message: "Need to update my phone number",
    status: "open",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_by_name: "Mike Landowner",
  },
];

// Flag to enable demo mode
export const DEMO_MODE = true;
